# Generated by Django 4.0.2 on 2022-02-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0007_alter_purchase_customer'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0006_customuser_remove_userprofile_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
