# Generated by Django 4.0.2 on 2022-02-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_store', '0003_alter_purchase_date_of_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_of_purchase',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='returnpurchase',
            name='time_of_request',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
