# Generated by Django 4.0.2 on 2022-02-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_avatar_alter_userprofile_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
